### ISSUE TITLE
Test benchmarks - CUDA version?

### ISSUE THREAD

**Issue by pedro77pl** [216k155/ccminer-phi-anxmod#10]
I compiled on Ubuntu 16.04 LTS wit downgraded CUDA to 8th revision. My performance on GTX1080ti is about 2-3MH/s lower than your tests. Can this be CUDA related or just difference between card models?

**Comment by anorganix** [comment]
Tests were made on Windows. Also, keep in mind that card models are different. 1080Ti tests were made on Gigabyte Aorus Xtreme Edition. Hope it helps.
