### ISSUE TITLE
CUDA 9.1, Ubuntu 16.04

### ISSUE THREAD

**Issue by kiwinesian** [216k155/ccminer-phi-anxmod#15]
Hey hey,

is it not possible to build it using CUDA 9.1?
Compilation went fine, but encounter the following error when trying to run it:

`Cuda error in func 'skein512_cpu_setBlock_80' at line 565 : invalid argument.
Cuda error in func 'skein512_cpu_setBlock_80' at line 565 : driver shutting down.
Cuda error in func 'scanhash_phi' at line 142 : driver shutting down.
Cuda error in func 'skein512_cpu_setBlock_80' at line 565 : driver shutting down.
Segmentation fault (core dumped)
`

or can anyone upload the built version with CUDA 8.0?

**Comment by pedro77pl** [comment]
Here you are mate. I had to zip the file as gitgub won't allow me to upload it otherwise. It's compiled with CUDA 8. I used it with SMOS rig, but it should work fine with other Linux distros. Compiled with Ubuntu 16.04.

[ccminer-phi-anxmod.zip](https://github.com/216k155/ccminer-phi-anxmod/files/1766622/ccminer-phi-anxmod.zip)

**Comment by kiwinesian** [comment]
Heyyy thanks so much for doing this!

Does it really improve the performance?
Im using CCMINER by tpruvot and for 1070, its pulling 17.1. Will it really
pull 19.8?

Thanks a lot for doing this though!

Kind regards,
ST

**Comment by pedro77pl** [comment]
Just  run it and compare ;)  I used it to mine RVN with PHI algo - not sure if standard CCMINER had this algo implemented.

**Comment by kiwinesian** [comment]
Thanks so much!

Yaa.. im worried that I might need to downgrade to 8.0. Not really sure if
want to spend the time downgrading if there isnt a lot of performance
improvement.. ;p

Thanks again!

Kind regards,
ST

**Comment by greerso** [comment]
Hey @pedro77pl I tried that binary in smOS and got illegal instruction errors.  Is it still working for you?
