### ISSUE TITLE
linux build?

### ISSUE THREAD

**Issue by huglester** [216k155/ccminer-phi-anxmod#2]
Hello

any info on how to build it on linux?

**Comment by fastworks** [comment]
Edit configure.sh to point to your CUDA install then run ./build.sh the pre-requisites are similar to all the other ccminer installs.

**Comment by siverpro** [comment]
I compiled this on Linux with Cuda9.1 and sm_61 for my 1080Ti cards, getting this error:
"Cuda error in func 'skein512_cpu_setBlock_80' at line 565 : invalid argument."
I've successfully compiled ccminer-Alexis with these settings and no problems..

**Comment by voipmonitor** [comment]
Hi, I have the exact same problem - "Cuda error in func 'skein512_cpu_setBlock_80' at line 565 : invalid argument."

I have nvidia-cuda-toolkit             9.0.176-2

Is this some incompatiblity with cuda 9 and 9.1 ? Should I try cuda 8 ? Or 9 beta?

**Comment by anorganix** [comment]
Please use CUDA 8 as it's tweaked (and tested) to offer best results with it.
