### ISSUE TITLE
Access denied on Win

### ISSUE THREAD

**Issue by djspacedevil** [216k155/ccminer-phi-anxmod#3]
Cannot run with virus programm is active. 
When run in VM without any securty program, the program dont run. 

It starts and ends directly.

**Comment by tpruvot** [comment]
cuda in a VM ? ps: never tried

**Comment by anorganix** [comment]
@djspacedevil It's getting flagged by your AV software because it has crypto-related code inside. You can always compile it from source if you don't feel confortable with using the provided binary. Use CUDA 8 and compile for 32-bit for best performance.
