### ISSUE TITLE
Got Trojan Alert on my windows PC at time of Unzipping files

### ISSUE THREAD

**Issue by raghuariga** [216k155/ccminer-phi-anxmod#5]
Hi All,

does anyone get Trojan Virus alert?

**Comment by oliveskin** [comment]
mining software usually gives a false positive. This is normal; you just have to white-list it.

**Comment by anorganix** [comment]
Thanks for the help @oliveskin, indeed it's a false positive triggered by the presence of hashing/crypto-related code.
