### ISSUE TITLE
rig 6 nvidia crash

### ISSUE THREAD

**Issue by gemini100** [216k155/ccminer-phi-anxmod#7]
i m using ccminer 2.2.2 for lux, it's disapointed, only small rig don't crash, but rigs with 6 gpu always crash
even if i decrease itensity to 14
so i try download your version and try anxmod
thank you for luxcoin

**Comment by gemini100** [comment]
thank you all my rigs mine for more than 20 hrs now with 1 hr of pause, great version

**Comment by anorganix** [comment]
Glad to hear. Good luck!
