### ISSUE TITLE
phi algo error

### ISSUE THREAD

**Issue by Eneen** [216k155/ccminer-phi-anxmod#9]
Under linux I've got such error when running anxmod:

Cuda error in func 'skein512_cpu_setBlock_80' at line 565 : invalid argument.
Cuda error in func 'scanhash_phi' at line 142 : driver shutting down.

Not sure where problem is, but reporting as might be a bug.

**Comment by gregfromo** [comment]
I get also error for algo PHI, when build against CUDA 9.1 (X64 & X86) under windows. 
Cuda 7.5 & 8 is ok, 9 I didn't test.

**Comment by venelin-mihaylov** [comment]
I get the same errr with linux, cuda 9.0. I guess the problem is with cuda 9.

**Comment by gamaraan** [comment]
Same here. Compiled against cuda 9.0 or 9.1 crashed right from the start with that error. Compiled with cuda 8.0 it worked. Ubuntu 16.04

**Comment by anorganix** [comment]
There was another issue with the exact same problem.

My answer there:
"Please use CUDA 8 as it's tweaked (and tested) to offer best results with it."
